apiVersion: v1
data:
  cert-dir: /certs
  debug: "false"
  disable-cert-rotation: "false"
  dry-run: "false"
  failure-policy: Ignore
  health-port: "9090"
  image: ghcr.io/google/k8s-digester
  metrics-port: "8888"
  offline: "false"
  port: "8443"
  replicas: "3"
  request-cpu: 100m
  request-ephemeral-storage: 256Mi
  request-memory: 256Mi
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
  name: setters
