apiVersion: v1
data:
  cert-dir: /certs
  debug: "false"
  disable-cert-rotation: "false"
  dry-run: "false"
  failure-policy: Ignore
  health-port: "9090"
  image: ghcr.io/google/github_com_google_k8s-digester:v0.1.8@sha256:03a70ba5c0e998aacb2926258ed2b0d32c4390c159e20f21e48f40fd574afd50
  metrics-port: "8888"
  offline: "false"
  port: "8443"
  replicas: "3"
  request-cpu: 100m
  request-ephemeral-storage: 256Mi
  request-memory: 256Mi
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
  name: setters
